#!/usr/bin/env python3
"""Deterministic local-module bundler; no remote fetches in the release."""
from pathlib import Path
import argparse
root = Path(__file__).resolve().parents[1]
files = sorted((root / 'src').rglob('*.lua'))
parts = ['-- Iris Drawing v1.0.0 | generated by scripts/build.py; edit src instead.',
         '-- Runtime contract and API: README.md', 'local loaders, cache = {}, {}',
         'local function require(name)',
         '    if cache[name] ~= nil then return cache[name] end',
         '    assert(loaders[name], "Unknown bundled module: " .. name)',
         '    local value = loaders[name]()', '    cache[name] = value', '    return value', 'end']
for file in files:
    name = '.'.join(file.relative_to(root / 'src').with_suffix('').parts)
    parts += [f'loaders["{name}"] = function()', file.read_text(encoding='utf-8-sig').rstrip(), 'end']
parts += ['return require("Library")', '']
content = '\n'.join(parts)
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
target = root / 'dist/Iris.lua'
if args.check:
    assert target.read_text(encoding='utf-8') == content, 'Bundle is stale; run scripts/build.py'
    print('Bundle is reproducible and current')
else:
    target.parent.mkdir(exist_ok=True)
    target.write_text(content, encoding='utf-8', newline='\n')
    print(f'Built {target.name}: {len(content.encode())} bytes, {len(files)} modules')
